name: Test
dist: focal
addons:
    apt:
        packages:
            - ffmpeg
            - git
            - git-lfs

language: python
python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"

# command to install dependencies
install:
    - pip install prometheus-client codecov

# command to run tests
script:
    - tests/runtests.sh
after_success:
    - codecov
